---
- name: Loop over Product Listings and attach them all
  ansible.builtin.include_tasks: attach_one_product_listing.yml
  loop: "{{ cert_item.pyxis_product_lists }}"
  loop_control:
    loop_var: pyxis_product_list_identifier
...
