---
- name: Check that organization_id is defined
  ansible.builtin.assert:
    that: "{{ organization_id }} is defined"

- name: Get certification cnf projects for the organization
  vars:
    pyxis_apikey: "{{ lookup('file', pyxis_apikey_path) }}"
  ansible.builtin.uri:
    url: >
      {{ catalog_url }}/vendors/org-id/{{ organization_id }}/projects/certification?filter=project_status%3D%3Dactive&page_size={{ page_size }}&page=0
    method: GET
    headers:
      X-API-KEY: "{{ pyxis_apikey }}"
    body_format: json
    status_code: 200
    timeout: 120
  register: cert_project_list_output
  retries: 20
  delay: 3
  until: not cert_project_list_output.failed

- name: Get certification projects information from the organization
  ansible.builtin.set_fact:
    cert_project_data: "{{ cert_project_list_output.json.data | json_query(query_data) }}"  # noqa: jinja[invalid]
  vars:
    query_data: "[?name == '{{ cert_item.cnf_name }}']"

- name: "Set fact if is already in an active certification project"
  ansible.builtin.set_fact:
    cert_project_exists_own_org: true
  loop: "{{ cert_project_data }}"
  loop_control:
    label: "{{ item._id }}"
  when:
    - cert_project_data | default([]) | length > 0
    - item.name == cert_item.cnf_name
    - item.project_status == "active"

- name: Notify if CNF is already in an active certification project
  ansible.builtin.debug:
    msg:
      - "CNF Name {{ cert_item.cnf_name }} is in process to get certify in another project of this organization"
      - "Review the following projects: {{ item._id }}"
      - "To continue, archive the project or reach out to support to delete it."
  loop: "{{ cert_project_data }}"
  loop_control:
    label: "{{ item._id }}"
  when:
    - cert_project_exists_own_org | default(false) | bool
    - item.name == cert_item.cnf_name
    - item.project_status == "active"

- name: Set project ID to reuse it later
  ansible.builtin.set_fact:
    cert_project_id: "{{ cert_project_data | json_query(query_data) | flatten | last }}"  # noqa: jinja[invalid]
  vars:
    query_data: "[]._id"
  when:
    - cert_project_exists_own_org | default(false) | bool
    - cert_project_data | default([]) | length > 0
...
