---
# TODO: this role should be merged with create_certification_project
- name: Create certification projects in a loop
  ansible.builtin.include_role:
    name: create_certification_project
  vars:
    product_type: "helmchart"
  loop: "{{ helmchart_to_certify }}"
  loop_control:
    loop_var: cert_item
...
